### ISSUE TITLE
Converting Level.sav generates a long Exception: Warning: EOF not reached

### ISSUE THREAD

**Issue by PinkkAqua** [wonjoonSeol-WS/Palworld-fix-uuid#2]
The initial part covnerting the first file works perfectly, but trying to convert the second file, the Level.sav it generates a huge exception and doesn't work.

![Screenshot 2024-08-02 101855](https://github.com/user-attachments/assets/02cdb15a-ece1-4c2c-b911-5db60c54e656)
[ScriptERror.txt](https://github.com/user-attachments/files/16471547/ScriptERror.txt)

**Comment by mhays705** [comment]
It's throwing the same exception for me. Any luck on a solution?

**Comment by wonjoonSeol-WS** [comment]
The issue is solved with the latest version. Please open the issue again if it persists!
